name: Tests
on:
  push:
  pull_request:
permissions:
  contents: read
jobs:
  wiki-plugin-migration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.13']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Test wiki plugin migration
        run: python -m unittest discover -s utilities/wiki-plugin-migration -v
